spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./extension
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: number
springdoc:
  swagger-ui:
    path: /swagger-ui.html
